/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BacktestResult = IDL.Record({
  'totalTrades' : IDL.Nat,
  'endDate' : IDL.Int,
  'losingTrades' : IDL.Nat,
  'sharpeRatio' : IDL.Text,
  'totalROI' : IDL.Text,
  'timestamp' : IDL.Int,
  'winningTrades' : IDL.Nat,
  'winRate' : IDL.Text,
  'strategyName' : IDL.Text,
  'maxDrawdown' : IDL.Text,
  'symbol' : IDL.Text,
  'startDate' : IDL.Int,
});
export const PositionBias = IDL.Variant({
  'bullish' : IDL.Null,
  'bearish' : IDL.Null,
  'neutral' : IDL.Null,
});
export const StrategyName = IDL.Text;
export const StrategyAnalysis = IDL.Record({
  'bias' : PositionBias,
  'agreement' : IDL.Bool,
  'details' : IDL.Text,
  'confidence' : IDL.Nat,
  'strategyName' : StrategyName,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TradeType = IDL.Variant({
  'scalping' : IDL.Null,
  'swing' : IDL.Null,
  'intraday' : IDL.Null,
});
export const SignalStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'expired' : IDL.Null,
  'triggered' : IDL.Null,
});
export const SignalType = IDL.Variant({
  'buy' : IDL.Null,
  'sell' : IDL.Null,
  'noTrade' : IDL.Null,
});
export const TradeSignal = IDL.Record({
  'leverage' : IDL.Nat,
  'tradeType' : TradeType,
  'riskPerTrade' : IDL.Nat,
  'reasoningBreakdown' : IDL.Text,
  'noTradeReason' : IDL.Opt(IDL.Text),
  'createdBy' : IDL.Principal,
  'contractType' : IDL.Variant({
    'futures' : IDL.Null,
    'stock' : IDL.Null,
    'options' : IDL.Null,
  }),
  'strategiesConfirmed' : IDL.Vec(StrategyName),
  'positionBias' : PositionBias,
  'positionSize' : IDL.Nat,
  'confidenceScore' : IDL.Nat,
  'target1' : IDL.Text,
  'target2' : IDL.Opt(IDL.Text),
  'target3' : IDL.Opt(IDL.Text),
  'rewardPotential' : IDL.Text,
  'stopLoss' : IDL.Text,
  'timestamp' : IDL.Int,
  'entryPrice' : IDL.Text,
  'signalStatus' : SignalStatus,
  'riskRewardRatio' : IDL.Text,
  'symbol' : IDL.Text,
  'signalType' : SignalType,
});
export const SignalId = IDL.Nat;
export const AlertPreference = IDL.Record({
  'minimumConfidenceForAlert' : IDL.Nat,
  'enableWebNotifications' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'verified' : IDL.Bool,
  'referralCode' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'email' : IDL.Text,
  'phoneNumber' : IDL.Opt(IDL.Text),
  'telegramId' : IDL.Opt(IDL.Text),
});
export const TradeOutcome = IDL.Variant({
  'win' : IDL.Null,
  'loss' : IDL.Null,
  'breakeven' : IDL.Null,
  'noTrade' : IDL.Null,
});
export const SignalFeedback = IDL.Record({
  'submittedBy' : IDL.Principal,
  'actualExit' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'outcome' : TradeOutcome,
  'actualEntry' : IDL.Text,
});
export const TradingPerformance = IDL.Record({
  'id' : IDL.Nat,
  'duration' : IDL.Nat,
  'returnPercentage' : IDL.Text,
  'finalCapital' : IDL.Nat,
  'profitLoss' : IDL.Text,
  'recordedBy' : IDL.Principal,
  'positionSize' : IDL.Nat,
  'capital' : IDL.Nat,
  'timestamp' : IDL.Int,
  'entryPrice' : IDL.Text,
  'stopLossHit' : IDL.Bool,
  'exitPrice' : IDL.Text,
  'riskRewardRatio' : IDL.Text,
  'symbol' : IDL.Text,
  'points' : IDL.Nat,
});
export const PlatformMetric = IDL.Record({
  'triggeredSignals' : IDL.Nat,
  'winningSignals' : IDL.Nat,
  'losingSignals' : IDL.Nat,
  'overallWinRate' : IDL.Text,
  'totalSignals' : IDL.Nat,
  'activeSignals' : IDL.Nat,
  'accuracy' : IDL.Text,
});
export const RiskSettings = IDL.Record({
  'riskRewardTarget' : IDL.Text,
  'drawdownLimit' : IDL.Nat,
  'maxLotSize' : IDL.Nat,
  'maxOpenTrades' : IDL.Nat,
  'riskPercentage' : IDL.Nat,
  'maxDailyLoss' : IDL.Nat,
  'capitalAmount' : IDL.Nat,
});
export const NotificationConfig = IDL.Record({
  'method' : IDL.Variant({
    'sms' : IDL.Null,
    'web' : IDL.Null,
    'push' : IDL.Null,
    'email' : IDL.Null,
    'inApp' : IDL.Null,
  }),
  'editBy' : IDL.Principal,
  'notificationType' : IDL.Variant({
    'news' : IDL.Null,
    'risk' : IDL.Null,
    'signal' : IDL.Null,
    'priceTarget' : IDL.Null,
  }),
  'user' : IDL.Principal,
  'isActive' : IDL.Bool,
  'frequency' : IDL.Variant({
    'monthly' : IDL.Null,
    'immediate' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBacktestResult' : IDL.Func([BacktestResult], [], []),
  'addToWatchlist' : IDL.Func([IDL.Text], [], []),
  'analyzeStrategy' : IDL.Func([StrategyAnalysis], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateMaxLotSize' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'checkAgreement' : IDL.Func(
      [IDL.Vec(StrategyAnalysis)],
      [IDL.Bool],
      ['query'],
    ),
  'createTradeSignal' : IDL.Func([TradeSignal], [SignalId], []),
  'deleteTradeSignal' : IDL.Func([SignalId], [], []),
  'getAlertPreference' : IDL.Func([], [AlertPreference], ['query']),
  'getAllSignalThresholds' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllStrategyWeights' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeedback' : IDL.Func([SignalId], [IDL.Vec(SignalFeedback)], ['query']),
  'getMarketRisk' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
  'getOverallPerformance' : IDL.Func(
      [],
      [IDL.Vec(TradingPerformance)],
      ['query'],
    ),
  'getPlatformMetrics' : IDL.Func([], [IDL.Opt(PlatformMetric)], ['query']),
  'getRiskSettings' : IDL.Func([], [RiskSettings], ['query']),
  'getSignalThreshold' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getSignalsByStatus' : IDL.Func(
      [SignalStatus],
      [IDL.Vec(TradeSignal)],
      ['query'],
    ),
  'getStrategyWeight' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getSystemStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalUsers' : IDL.Nat,
          'totalSignals' : IDL.Nat,
          'activeSignals' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTradeSignal' : IDL.Func([SignalId], [IDL.Opt(TradeSignal)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPatternPresent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'recordFeedback' : IDL.Func([SignalId, SignalFeedback], [], []),
  'recordPerformance' : IDL.Func([TradingPerformance], [], []),
  'removeFromWatchlistProcess' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendTradeNotification' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setAlertPreference' : IDL.Func([AlertPreference], [], []),
  'setNotificationConfig' : IDL.Func([NotificationConfig], [], []),
  'setRiskSettings' : IDL.Func([RiskSettings], [], []),
  'setSignalThreshold' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'setStrategyWeight' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateFeedback' : IDL.Func([SignalId, SignalFeedback], [], []),
  'updatePlatformMetrics' : IDL.Func([PlatformMetric], [], []),
  'updateRiskProfile' : IDL.Func([RiskSettings], [], []),
  'updateSignalStatus' : IDL.Func([SignalId, SignalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BacktestResult = IDL.Record({
    'totalTrades' : IDL.Nat,
    'endDate' : IDL.Int,
    'losingTrades' : IDL.Nat,
    'sharpeRatio' : IDL.Text,
    'totalROI' : IDL.Text,
    'timestamp' : IDL.Int,
    'winningTrades' : IDL.Nat,
    'winRate' : IDL.Text,
    'strategyName' : IDL.Text,
    'maxDrawdown' : IDL.Text,
    'symbol' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const PositionBias = IDL.Variant({
    'bullish' : IDL.Null,
    'bearish' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const StrategyName = IDL.Text;
  const StrategyAnalysis = IDL.Record({
    'bias' : PositionBias,
    'agreement' : IDL.Bool,
    'details' : IDL.Text,
    'confidence' : IDL.Nat,
    'strategyName' : StrategyName,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TradeType = IDL.Variant({
    'scalping' : IDL.Null,
    'swing' : IDL.Null,
    'intraday' : IDL.Null,
  });
  const SignalStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'expired' : IDL.Null,
    'triggered' : IDL.Null,
  });
  const SignalType = IDL.Variant({
    'buy' : IDL.Null,
    'sell' : IDL.Null,
    'noTrade' : IDL.Null,
  });
  const TradeSignal = IDL.Record({
    'leverage' : IDL.Nat,
    'tradeType' : TradeType,
    'riskPerTrade' : IDL.Nat,
    'reasoningBreakdown' : IDL.Text,
    'noTradeReason' : IDL.Opt(IDL.Text),
    'createdBy' : IDL.Principal,
    'contractType' : IDL.Variant({
      'futures' : IDL.Null,
      'stock' : IDL.Null,
      'options' : IDL.Null,
    }),
    'strategiesConfirmed' : IDL.Vec(StrategyName),
    'positionBias' : PositionBias,
    'positionSize' : IDL.Nat,
    'confidenceScore' : IDL.Nat,
    'target1' : IDL.Text,
    'target2' : IDL.Opt(IDL.Text),
    'target3' : IDL.Opt(IDL.Text),
    'rewardPotential' : IDL.Text,
    'stopLoss' : IDL.Text,
    'timestamp' : IDL.Int,
    'entryPrice' : IDL.Text,
    'signalStatus' : SignalStatus,
    'riskRewardRatio' : IDL.Text,
    'symbol' : IDL.Text,
    'signalType' : SignalType,
  });
  const SignalId = IDL.Nat;
  const AlertPreference = IDL.Record({
    'minimumConfidenceForAlert' : IDL.Nat,
    'enableWebNotifications' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'verified' : IDL.Bool,
    'referralCode' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'email' : IDL.Text,
    'phoneNumber' : IDL.Opt(IDL.Text),
    'telegramId' : IDL.Opt(IDL.Text),
  });
  const TradeOutcome = IDL.Variant({
    'win' : IDL.Null,
    'loss' : IDL.Null,
    'breakeven' : IDL.Null,
    'noTrade' : IDL.Null,
  });
  const SignalFeedback = IDL.Record({
    'submittedBy' : IDL.Principal,
    'actualExit' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'outcome' : TradeOutcome,
    'actualEntry' : IDL.Text,
  });
  const TradingPerformance = IDL.Record({
    'id' : IDL.Nat,
    'duration' : IDL.Nat,
    'returnPercentage' : IDL.Text,
    'finalCapital' : IDL.Nat,
    'profitLoss' : IDL.Text,
    'recordedBy' : IDL.Principal,
    'positionSize' : IDL.Nat,
    'capital' : IDL.Nat,
    'timestamp' : IDL.Int,
    'entryPrice' : IDL.Text,
    'stopLossHit' : IDL.Bool,
    'exitPrice' : IDL.Text,
    'riskRewardRatio' : IDL.Text,
    'symbol' : IDL.Text,
    'points' : IDL.Nat,
  });
  const PlatformMetric = IDL.Record({
    'triggeredSignals' : IDL.Nat,
    'winningSignals' : IDL.Nat,
    'losingSignals' : IDL.Nat,
    'overallWinRate' : IDL.Text,
    'totalSignals' : IDL.Nat,
    'activeSignals' : IDL.Nat,
    'accuracy' : IDL.Text,
  });
  const RiskSettings = IDL.Record({
    'riskRewardTarget' : IDL.Text,
    'drawdownLimit' : IDL.Nat,
    'maxLotSize' : IDL.Nat,
    'maxOpenTrades' : IDL.Nat,
    'riskPercentage' : IDL.Nat,
    'maxDailyLoss' : IDL.Nat,
    'capitalAmount' : IDL.Nat,
  });
  const NotificationConfig = IDL.Record({
    'method' : IDL.Variant({
      'sms' : IDL.Null,
      'web' : IDL.Null,
      'push' : IDL.Null,
      'email' : IDL.Null,
      'inApp' : IDL.Null,
    }),
    'editBy' : IDL.Principal,
    'notificationType' : IDL.Variant({
      'news' : IDL.Null,
      'risk' : IDL.Null,
      'signal' : IDL.Null,
      'priceTarget' : IDL.Null,
    }),
    'user' : IDL.Principal,
    'isActive' : IDL.Bool,
    'frequency' : IDL.Variant({
      'monthly' : IDL.Null,
      'immediate' : IDL.Null,
      'daily' : IDL.Null,
      'weekly' : IDL.Null,
    }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBacktestResult' : IDL.Func([BacktestResult], [], []),
    'addToWatchlist' : IDL.Func([IDL.Text], [], []),
    'analyzeStrategy' : IDL.Func([StrategyAnalysis], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateMaxLotSize' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'checkAgreement' : IDL.Func(
        [IDL.Vec(StrategyAnalysis)],
        [IDL.Bool],
        ['query'],
      ),
    'createTradeSignal' : IDL.Func([TradeSignal], [SignalId], []),
    'deleteTradeSignal' : IDL.Func([SignalId], [], []),
    'getAlertPreference' : IDL.Func([], [AlertPreference], ['query']),
    'getAllSignalThresholds' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllStrategyWeights' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeedback' : IDL.Func([SignalId], [IDL.Vec(SignalFeedback)], ['query']),
    'getMarketRisk' : IDL.Func([IDL.Nat], [IDL.Text], ['query']),
    'getOverallPerformance' : IDL.Func(
        [],
        [IDL.Vec(TradingPerformance)],
        ['query'],
      ),
    'getPlatformMetrics' : IDL.Func([], [IDL.Opt(PlatformMetric)], ['query']),
    'getRiskSettings' : IDL.Func([], [RiskSettings], ['query']),
    'getSignalThreshold' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getSignalsByStatus' : IDL.Func(
        [SignalStatus],
        [IDL.Vec(TradeSignal)],
        ['query'],
      ),
    'getStrategyWeight' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getSystemStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalUsers' : IDL.Nat,
            'totalSignals' : IDL.Nat,
            'activeSignals' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTradeSignal' : IDL.Func([SignalId], [IDL.Opt(TradeSignal)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPatternPresent' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'recordFeedback' : IDL.Func([SignalId, SignalFeedback], [], []),
    'recordPerformance' : IDL.Func([TradingPerformance], [], []),
    'removeFromWatchlistProcess' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendTradeNotification' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setAlertPreference' : IDL.Func([AlertPreference], [], []),
    'setNotificationConfig' : IDL.Func([NotificationConfig], [], []),
    'setRiskSettings' : IDL.Func([RiskSettings], [], []),
    'setSignalThreshold' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'setStrategyWeight' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateFeedback' : IDL.Func([SignalId, SignalFeedback], [], []),
    'updatePlatformMetrics' : IDL.Func([PlatformMetric], [], []),
    'updateRiskProfile' : IDL.Func([RiskSettings], [], []),
    'updateSignalStatus' : IDL.Func([SignalId, SignalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };