/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlertPreference {
  'minimumConfidenceForAlert' : bigint,
  'enableWebNotifications' : boolean,
}
export interface BacktestResult {
  'totalTrades' : bigint,
  'endDate' : bigint,
  'losingTrades' : bigint,
  'sharpeRatio' : string,
  'totalROI' : string,
  'timestamp' : bigint,
  'winningTrades' : bigint,
  'winRate' : string,
  'strategyName' : string,
  'maxDrawdown' : string,
  'symbol' : string,
  'startDate' : bigint,
}
export interface NotificationConfig {
  'method' : { 'sms' : null } |
    { 'web' : null } |
    { 'push' : null } |
    { 'email' : null } |
    { 'inApp' : null },
  'editBy' : Principal,
  'notificationType' : { 'news' : null } |
    { 'risk' : null } |
    { 'signal' : null } |
    { 'priceTarget' : null },
  'user' : Principal,
  'isActive' : boolean,
  'frequency' : { 'monthly' : null } |
    { 'immediate' : null } |
    { 'daily' : null } |
    { 'weekly' : null },
}
export interface PlatformMetric {
  'triggeredSignals' : bigint,
  'winningSignals' : bigint,
  'losingSignals' : bigint,
  'overallWinRate' : string,
  'totalSignals' : bigint,
  'activeSignals' : bigint,
  'accuracy' : string,
}
export type PositionBias = { 'bullish' : null } |
  { 'bearish' : null } |
  { 'neutral' : null };
export interface RiskSettings {
  'riskRewardTarget' : string,
  'drawdownLimit' : bigint,
  'maxLotSize' : bigint,
  'maxOpenTrades' : bigint,
  'riskPercentage' : bigint,
  'maxDailyLoss' : bigint,
  'capitalAmount' : bigint,
}
export interface SignalFeedback {
  'submittedBy' : Principal,
  'actualExit' : string,
  'notes' : string,
  'timestamp' : bigint,
  'outcome' : TradeOutcome,
  'actualEntry' : string,
}
export type SignalId = bigint;
export type SignalStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'expired' : null } |
  { 'triggered' : null };
export type SignalType = { 'buy' : null } |
  { 'sell' : null } |
  { 'noTrade' : null };
export interface StrategyAnalysis {
  'bias' : PositionBias,
  'agreement' : boolean,
  'details' : string,
  'confidence' : bigint,
  'strategyName' : StrategyName,
}
export type StrategyName = string;
export type TradeOutcome = { 'win' : null } |
  { 'loss' : null } |
  { 'breakeven' : null } |
  { 'noTrade' : null };
export interface TradeSignal {
  'leverage' : bigint,
  'tradeType' : TradeType,
  'riskPerTrade' : bigint,
  'reasoningBreakdown' : string,
  'noTradeReason' : [] | [string],
  'createdBy' : Principal,
  'contractType' : { 'futures' : null } |
    { 'stock' : null } |
    { 'options' : null },
  'strategiesConfirmed' : Array<StrategyName>,
  'positionBias' : PositionBias,
  'positionSize' : bigint,
  'confidenceScore' : bigint,
  'target1' : string,
  'target2' : [] | [string],
  'target3' : [] | [string],
  'rewardPotential' : string,
  'stopLoss' : string,
  'timestamp' : bigint,
  'entryPrice' : string,
  'signalStatus' : SignalStatus,
  'riskRewardRatio' : string,
  'symbol' : string,
  'signalType' : SignalType,
}
export type TradeType = { 'scalping' : null } |
  { 'swing' : null } |
  { 'intraday' : null };
export interface TradingPerformance {
  'id' : bigint,
  'duration' : bigint,
  'returnPercentage' : string,
  'finalCapital' : bigint,
  'profitLoss' : string,
  'recordedBy' : Principal,
  'positionSize' : bigint,
  'capital' : bigint,
  'timestamp' : bigint,
  'entryPrice' : string,
  'stopLossHit' : boolean,
  'exitPrice' : string,
  'riskRewardRatio' : string,
  'symbol' : string,
  'points' : bigint,
}
export interface UserProfile {
  'verified' : boolean,
  'referralCode' : [] | [string],
  'username' : string,
  'email' : string,
  'phoneNumber' : [] | [string],
  'telegramId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBacktestResult' : ActorMethod<[BacktestResult], undefined>,
  'addToWatchlist' : ActorMethod<[string], undefined>,
  'analyzeStrategy' : ActorMethod<[StrategyAnalysis], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateMaxLotSize' : ActorMethod<[bigint, bigint, bigint], bigint>,
  'checkAgreement' : ActorMethod<[Array<StrategyAnalysis>], boolean>,
  'createTradeSignal' : ActorMethod<[TradeSignal], SignalId>,
  'deleteTradeSignal' : ActorMethod<[SignalId], undefined>,
  'getAlertPreference' : ActorMethod<[], AlertPreference>,
  'getAllSignalThresholds' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllStrategyWeights' : ActorMethod<[], Array<[string, bigint]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeedback' : ActorMethod<[SignalId], Array<SignalFeedback>>,
  'getMarketRisk' : ActorMethod<[bigint], string>,
  'getOverallPerformance' : ActorMethod<[], Array<TradingPerformance>>,
  'getPlatformMetrics' : ActorMethod<[], [] | [PlatformMetric]>,
  'getRiskSettings' : ActorMethod<[], RiskSettings>,
  'getSignalThreshold' : ActorMethod<[string], [] | [bigint]>,
  'getSignalsByStatus' : ActorMethod<[SignalStatus], Array<TradeSignal>>,
  'getStrategyWeight' : ActorMethod<[string], [] | [bigint]>,
  'getSystemStats' : ActorMethod<
    [],
    { 'totalUsers' : bigint, 'totalSignals' : bigint, 'activeSignals' : bigint }
  >,
  'getTradeSignal' : ActorMethod<[SignalId], [] | [TradeSignal]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatchlist' : ActorMethod<[], Array<string>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPatternPresent' : ActorMethod<[string, string], boolean>,
  'recordFeedback' : ActorMethod<[SignalId, SignalFeedback], undefined>,
  'recordPerformance' : ActorMethod<[TradingPerformance], undefined>,
  'removeFromWatchlistProcess' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendTradeNotification' : ActorMethod<[string, bigint], undefined>,
  'setAlertPreference' : ActorMethod<[AlertPreference], undefined>,
  'setNotificationConfig' : ActorMethod<[NotificationConfig], undefined>,
  'setRiskSettings' : ActorMethod<[RiskSettings], undefined>,
  'setSignalThreshold' : ActorMethod<[string, bigint], undefined>,
  'setStrategyWeight' : ActorMethod<[string, bigint], undefined>,
  'updateFeedback' : ActorMethod<[SignalId, SignalFeedback], undefined>,
  'updatePlatformMetrics' : ActorMethod<[PlatformMetric], undefined>,
  'updateRiskProfile' : ActorMethod<[RiskSettings], undefined>,
  'updateSignalStatus' : ActorMethod<[SignalId, SignalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];