/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type SignalId = bigint;
export interface BacktestResult {
    totalTrades: bigint;
    endDate: bigint;
    losingTrades: bigint;
    sharpeRatio: string;
    totalROI: string;
    timestamp: bigint;
    winningTrades: bigint;
    winRate: string;
    strategyName: string;
    maxDrawdown: string;
    symbol: string;
    startDate: bigint;
}
export interface RiskSettings {
    riskRewardTarget: string;
    drawdownLimit: bigint;
    maxLotSize: bigint;
    maxOpenTrades: bigint;
    riskPercentage: bigint;
    maxDailyLoss: bigint;
    capitalAmount: bigint;
}
export interface TradingPerformance {
    id: bigint;
    duration: bigint;
    returnPercentage: string;
    finalCapital: bigint;
    profitLoss: string;
    recordedBy: Principal;
    positionSize: bigint;
    capital: bigint;
    timestamp: bigint;
    entryPrice: string;
    stopLossHit: boolean;
    exitPrice: string;
    riskRewardRatio: string;
    symbol: string;
    points: bigint;
}
export interface TradeSignal {
    leverage: bigint;
    tradeType: TradeType;
    riskPerTrade: bigint;
    reasoningBreakdown: string;
    noTradeReason?: string;
    createdBy: Principal;
    contractType: Variant_futures_stock_options;
    strategiesConfirmed: Array<StrategyName>;
    positionBias: PositionBias;
    positionSize: bigint;
    confidenceScore: bigint;
    target1: string;
    target2?: string;
    target3?: string;
    rewardPotential: string;
    stopLoss: string;
    timestamp: bigint;
    entryPrice: string;
    signalStatus: SignalStatus;
    riskRewardRatio: string;
    symbol: string;
    signalType: SignalType;
}
export interface SignalFeedback {
    submittedBy: Principal;
    actualExit: string;
    notes: string;
    timestamp: bigint;
    outcome: TradeOutcome;
    actualEntry: string;
}
export interface PlatformMetric {
    triggeredSignals: bigint;
    winningSignals: bigint;
    losingSignals: bigint;
    overallWinRate: string;
    totalSignals: bigint;
    activeSignals: bigint;
    accuracy: string;
}
export interface AlertPreference {
    minimumConfidenceForAlert: bigint;
    enableWebNotifications: boolean;
}
export interface NotificationConfig {
    method: Variant_sms_web_push_email_inApp;
    editBy: Principal;
    notificationType: Variant_news_risk_signal_priceTarget;
    user: Principal;
    isActive: boolean;
    frequency: Variant_monthly_immediate_daily_weekly;
}
export interface StrategyAnalysis {
    bias: PositionBias;
    agreement: boolean;
    details: string;
    confidence: bigint;
    strategyName: StrategyName;
}
export type StrategyName = string;
export interface UserProfile {
    verified: boolean;
    referralCode?: string;
    username: string;
    email: string;
    phoneNumber?: string;
    telegramId?: string;
}
export enum PositionBias {
    bullish = "bullish",
    bearish = "bearish",
    neutral = "neutral"
}
export enum SignalStatus {
    active = "active",
    cancelled = "cancelled",
    expired = "expired",
    triggered = "triggered"
}
export enum SignalType {
    buy = "buy",
    sell = "sell",
    noTrade = "noTrade"
}
export enum TradeOutcome {
    win = "win",
    loss = "loss",
    breakeven = "breakeven",
    noTrade = "noTrade"
}
export enum TradeType {
    scalping = "scalping",
    swing = "swing",
    intraday = "intraday"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_futures_stock_options {
    futures = "futures",
    stock = "stock",
    options = "options"
}
export enum Variant_monthly_immediate_daily_weekly {
    monthly = "monthly",
    immediate = "immediate",
    daily = "daily",
    weekly = "weekly"
}
export enum Variant_news_risk_signal_priceTarget {
    news = "news",
    risk = "risk",
    signal = "signal",
    priceTarget = "priceTarget"
}
export enum Variant_sms_web_push_email_inApp {
    sms = "sms",
    web = "web",
    push = "push",
    email = "email",
    inApp = "inApp"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBacktestResult(backtestResult: BacktestResult): Promise<void>;
    addToWatchlist(symbol: string): Promise<void>;
    analyzeStrategy(strategyAnalysis: StrategyAnalysis): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateMaxLotSize(capitalAmount: bigint, riskPercentage: bigint, lotSizePerRisk: bigint): Promise<bigint>;
    checkAgreement(strategies: Array<StrategyAnalysis>): Promise<boolean>;
    createTradeSignal(signal: TradeSignal): Promise<SignalId>;
    deleteTradeSignal(signalId: SignalId): Promise<void>;
    getAlertPreference(): Promise<AlertPreference>;
    getAllSignalThresholds(): Promise<Array<[string, bigint]>>;
    getAllStrategyWeights(): Promise<Array<[string, bigint]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFeedback(signalId: SignalId): Promise<Array<SignalFeedback>>;
    getMarketRisk(riskLevel: bigint): Promise<string>;
    getOverallPerformance(): Promise<Array<TradingPerformance>>;
    getPlatformMetrics(): Promise<PlatformMetric | null>;
    getRiskSettings(): Promise<RiskSettings>;
    getSignalThreshold(thresholdName: string): Promise<bigint | null>;
    getSignalsByStatus(signalStatus: SignalStatus): Promise<Array<TradeSignal>>;
    getStrategyWeight(strategyName: string): Promise<bigint | null>;
    getSystemStats(): Promise<{
        totalUsers: bigint;
        totalSignals: bigint;
        activeSignals: bigint;
    }>;
    getTradeSignal(signalId: SignalId): Promise<TradeSignal | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWatchlist(): Promise<Array<string>>;
    isCallerAdmin(): Promise<boolean>;
    isPatternPresent(text: string, pattern: string): Promise<boolean>;
    recordFeedback(signalId: SignalId, signalFeedback: SignalFeedback): Promise<void>;
    recordPerformance(performance: TradingPerformance): Promise<void>;
    removeFromWatchlistProcess(symbol: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendTradeNotification(symbol: string, price: bigint): Promise<void>;
    setAlertPreference(preference: AlertPreference): Promise<void>;
    setNotificationConfig(notificationConfig: NotificationConfig): Promise<void>;
    setRiskSettings(settings: RiskSettings): Promise<void>;
    setSignalThreshold(thresholdName: string, value: bigint): Promise<void>;
    setStrategyWeight(strategyName: string, weight: bigint): Promise<void>;
    updateFeedback(signalId: SignalId, signalFeedback: SignalFeedback): Promise<void>;
    updatePlatformMetrics(metrics: PlatformMetric): Promise<void>;
    updateRiskProfile(settings: RiskSettings): Promise<void>;
    updateSignalStatus(signalId: SignalId, signalStatus: SignalStatus): Promise<void>;
}
import type { NotificationConfig as _NotificationConfig, PlatformMetric as _PlatformMetric, PositionBias as _PositionBias, SignalFeedback as _SignalFeedback, SignalStatus as _SignalStatus, SignalType as _SignalType, StrategyAnalysis as _StrategyAnalysis, StrategyName as _StrategyName, TradeOutcome as _TradeOutcome, TradeSignal as _TradeSignal, TradeType as _TradeType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBacktestResult(arg0: BacktestResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBacktestResult(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBacktestResult(arg0);
            return result;
        }
    }
    async addToWatchlist(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWatchlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWatchlist(arg0);
            return result;
        }
    }
    async analyzeStrategy(arg0: StrategyAnalysis): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeStrategy(to_candid_StrategyAnalysis_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeStrategy(to_candid_StrategyAnalysis_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateMaxLotSize(arg0: bigint, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateMaxLotSize(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateMaxLotSize(arg0, arg1, arg2);
            return result;
        }
    }
    async checkAgreement(arg0: Array<StrategyAnalysis>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAgreement(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAgreement(to_candid_vec_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTradeSignal(arg0: TradeSignal): Promise<SignalId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTradeSignal(to_candid_TradeSignal_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTradeSignal(to_candid_TradeSignal_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteTradeSignal(arg0: SignalId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTradeSignal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTradeSignal(arg0);
            return result;
        }
    }
    async getAlertPreference(): Promise<AlertPreference> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlertPreference();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlertPreference();
            return result;
        }
    }
    async getAllSignalThresholds(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSignalThresholds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSignalThresholds();
            return result;
        }
    }
    async getAllStrategyWeights(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStrategyWeights();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStrategyWeights();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeedback(arg0: SignalId): Promise<Array<SignalFeedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedback(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedback(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketRisk(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketRisk(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketRisk(arg0);
            return result;
        }
    }
    async getOverallPerformance(): Promise<Array<TradingPerformance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverallPerformance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverallPerformance();
            return result;
        }
    }
    async getPlatformMetrics(): Promise<PlatformMetric | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformMetrics();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformMetrics();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRiskSettings(): Promise<RiskSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getRiskSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRiskSettings();
            return result;
        }
    }
    async getSignalThreshold(arg0: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignalThreshold(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignalThreshold(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSignalsByStatus(arg0: SignalStatus): Promise<Array<TradeSignal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSignalsByStatus(to_candid_SignalStatus_n13(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSignalsByStatus(to_candid_SignalStatus_n13(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStrategyWeight(arg0: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStrategyWeight(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStrategyWeight(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemStats(): Promise<{
        totalUsers: bigint;
        totalSignals: bigint;
        activeSignals: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemStats();
            return result;
        }
    }
    async getTradeSignal(arg0: SignalId): Promise<TradeSignal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTradeSignal(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTradeSignal(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWatchlist(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isPatternPresent(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPatternPresent(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPatternPresent(arg0, arg1);
            return result;
        }
    }
    async recordFeedback(arg0: SignalId, arg1: SignalFeedback): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordFeedback(arg0, to_candid_SignalFeedback_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordFeedback(arg0, to_candid_SignalFeedback_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async recordPerformance(arg0: TradingPerformance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPerformance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPerformance(arg0);
            return result;
        }
    }
    async removeFromWatchlistProcess(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWatchlistProcess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWatchlistProcess(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n47(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendTradeNotification(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTradeNotification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTradeNotification(arg0, arg1);
            return result;
        }
    }
    async setAlertPreference(arg0: AlertPreference): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAlertPreference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAlertPreference(arg0);
            return result;
        }
    }
    async setNotificationConfig(arg0: NotificationConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setNotificationConfig(to_candid_NotificationConfig_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNotificationConfig(to_candid_NotificationConfig_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setRiskSettings(arg0: RiskSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRiskSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRiskSettings(arg0);
            return result;
        }
    }
    async setSignalThreshold(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSignalThreshold(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSignalThreshold(arg0, arg1);
            return result;
        }
    }
    async setStrategyWeight(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStrategyWeight(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStrategyWeight(arg0, arg1);
            return result;
        }
    }
    async updateFeedback(arg0: SignalId, arg1: SignalFeedback): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeedback(arg0, to_candid_SignalFeedback_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeedback(arg0, to_candid_SignalFeedback_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePlatformMetrics(arg0: PlatformMetric): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlatformMetrics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlatformMetrics(arg0);
            return result;
        }
    }
    async updateRiskProfile(arg0: RiskSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRiskProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRiskProfile(arg0);
            return result;
        }
    }
    async updateSignalStatus(arg0: SignalId, arg1: SignalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSignalStatus(arg0, to_candid_SignalStatus_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSignalStatus(arg0, to_candid_SignalStatus_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_PositionBias_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PositionBias): PositionBias {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_SignalFeedback_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalFeedback): SignalFeedback {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_SignalStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalStatus): SignalStatus {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_SignalType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalType): SignalType {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_TradeOutcome_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeOutcome): TradeOutcome {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_TradeSignal_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeSignal): TradeSignal {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_TradeType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeType): TradeType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlatformMetric]): PlatformMetric | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TradeSignal]): TradeSignal | null {
    return value.length === 0 ? null : from_candid_TradeSignal_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: boolean;
    referralCode: [] | [string];
    username: string;
    email: string;
    phoneNumber: [] | [string];
    telegramId: [] | [string];
}): {
    verified: boolean;
    referralCode?: string;
    username: string;
    email: string;
    phoneNumber?: string;
    telegramId?: string;
} {
    return {
        verified: value.verified,
        referralCode: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.referralCode)),
        username: value.username,
        email: value.email,
        phoneNumber: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.phoneNumber)),
        telegramId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.telegramId))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submittedBy: Principal;
    actualExit: string;
    notes: string;
    timestamp: bigint;
    outcome: _TradeOutcome;
    actualEntry: string;
}): {
    submittedBy: Principal;
    actualExit: string;
    notes: string;
    timestamp: bigint;
    outcome: TradeOutcome;
    actualEntry: string;
} {
    return {
        submittedBy: value.submittedBy,
        actualExit: value.actualExit,
        notes: value.notes,
        timestamp: value.timestamp,
        outcome: from_candid_TradeOutcome_n26(_uploadFile, _downloadFile, value.outcome),
        actualEntry: value.actualEntry
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leverage: bigint;
    tradeType: _TradeType;
    riskPerTrade: bigint;
    reasoningBreakdown: string;
    noTradeReason: [] | [string];
    createdBy: Principal;
    contractType: {
        futures: null;
    } | {
        stock: null;
    } | {
        options: null;
    };
    strategiesConfirmed: Array<_StrategyName>;
    positionBias: _PositionBias;
    positionSize: bigint;
    confidenceScore: bigint;
    target1: string;
    target2: [] | [string];
    target3: [] | [string];
    rewardPotential: string;
    stopLoss: string;
    timestamp: bigint;
    entryPrice: string;
    signalStatus: _SignalStatus;
    riskRewardRatio: string;
    symbol: string;
    signalType: _SignalType;
}): {
    leverage: bigint;
    tradeType: TradeType;
    riskPerTrade: bigint;
    reasoningBreakdown: string;
    noTradeReason?: string;
    createdBy: Principal;
    contractType: Variant_futures_stock_options;
    strategiesConfirmed: Array<StrategyName>;
    positionBias: PositionBias;
    positionSize: bigint;
    confidenceScore: bigint;
    target1: string;
    target2?: string;
    target3?: string;
    rewardPotential: string;
    stopLoss: string;
    timestamp: bigint;
    entryPrice: string;
    signalStatus: SignalStatus;
    riskRewardRatio: string;
    symbol: string;
    signalType: SignalType;
} {
    return {
        leverage: value.leverage,
        tradeType: from_candid_TradeType_n33(_uploadFile, _downloadFile, value.tradeType),
        riskPerTrade: value.riskPerTrade,
        reasoningBreakdown: value.reasoningBreakdown,
        noTradeReason: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.noTradeReason)),
        createdBy: value.createdBy,
        contractType: from_candid_variant_n35(_uploadFile, _downloadFile, value.contractType),
        strategiesConfirmed: value.strategiesConfirmed,
        positionBias: from_candid_PositionBias_n36(_uploadFile, _downloadFile, value.positionBias),
        positionSize: value.positionSize,
        confidenceScore: value.confidenceScore,
        target1: value.target1,
        target2: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.target2)),
        target3: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.target3)),
        rewardPotential: value.rewardPotential,
        stopLoss: value.stopLoss,
        timestamp: value.timestamp,
        entryPrice: value.entryPrice,
        signalStatus: from_candid_SignalStatus_n38(_uploadFile, _downloadFile, value.signalStatus),
        riskRewardRatio: value.riskRewardRatio,
        symbol: value.symbol,
        signalType: from_candid_SignalType_n40(_uploadFile, _downloadFile, value.signalType)
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    win: null;
} | {
    loss: null;
} | {
    breakeven: null;
} | {
    noTrade: null;
}): TradeOutcome {
    return "win" in value ? TradeOutcome.win : "loss" in value ? TradeOutcome.loss : "breakeven" in value ? TradeOutcome.breakeven : "noTrade" in value ? TradeOutcome.noTrade : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scalping: null;
} | {
    swing: null;
} | {
    intraday: null;
}): TradeType {
    return "scalping" in value ? TradeType.scalping : "swing" in value ? TradeType.swing : "intraday" in value ? TradeType.intraday : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    futures: null;
} | {
    stock: null;
} | {
    options: null;
}): Variant_futures_stock_options {
    return "futures" in value ? Variant_futures_stock_options.futures : "stock" in value ? Variant_futures_stock_options.stock : "options" in value ? Variant_futures_stock_options.options : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bullish: null;
} | {
    bearish: null;
} | {
    neutral: null;
}): PositionBias {
    return "bullish" in value ? PositionBias.bullish : "bearish" in value ? PositionBias.bearish : "neutral" in value ? PositionBias.neutral : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
} | {
    triggered: null;
}): SignalStatus {
    return "active" in value ? SignalStatus.active : "cancelled" in value ? SignalStatus.cancelled : "expired" in value ? SignalStatus.expired : "triggered" in value ? SignalStatus.triggered : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
} | {
    noTrade: null;
}): SignalType {
    return "buy" in value ? SignalType.buy : "sell" in value ? SignalType.sell : "noTrade" in value ? SignalType.noTrade : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SignalFeedback>): Array<SignalFeedback> {
    return value.map((x)=>from_candid_SignalFeedback_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TradeSignal>): Array<TradeSignal> {
    return value.map((x)=>from_candid_TradeSignal_n31(_uploadFile, _downloadFile, x));
}
function to_candid_NotificationConfig_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationConfig): _NotificationConfig {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_PositionBias_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositionBias): _PositionBias {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SignalFeedback_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalFeedback): _SignalFeedback {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_SignalStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalStatus): _SignalStatus {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_SignalType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalType): _SignalType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_StrategyAnalysis_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StrategyAnalysis): _StrategyAnalysis {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TradeOutcome_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeOutcome): _TradeOutcome {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_TradeSignal_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeSignal): _TradeSignal {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_TradeType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): _TradeType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bias: PositionBias;
    agreement: boolean;
    details: string;
    confidence: bigint;
    strategyName: StrategyName;
}): {
    bias: _PositionBias;
    agreement: boolean;
    details: string;
    confidence: bigint;
    strategyName: _StrategyName;
} {
    return {
        bias: to_candid_PositionBias_n3(_uploadFile, _downloadFile, value.bias),
        agreement: value.agreement,
        details: value.details,
        confidence: value.confidence,
        strategyName: value.strategyName
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submittedBy: Principal;
    actualExit: string;
    notes: string;
    timestamp: bigint;
    outcome: TradeOutcome;
    actualEntry: string;
}): {
    submittedBy: Principal;
    actualExit: string;
    notes: string;
    timestamp: bigint;
    outcome: _TradeOutcome;
    actualEntry: string;
} {
    return {
        submittedBy: value.submittedBy,
        actualExit: value.actualExit,
        notes: value.notes,
        timestamp: value.timestamp,
        outcome: to_candid_TradeOutcome_n45(_uploadFile, _downloadFile, value.outcome),
        actualEntry: value.actualEntry
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: boolean;
    referralCode?: string;
    username: string;
    email: string;
    phoneNumber?: string;
    telegramId?: string;
}): {
    verified: boolean;
    referralCode: [] | [string];
    username: string;
    email: string;
    phoneNumber: [] | [string];
    telegramId: [] | [string];
} {
    return {
        verified: value.verified,
        referralCode: value.referralCode ? candid_some(value.referralCode) : candid_none(),
        username: value.username,
        email: value.email,
        phoneNumber: value.phoneNumber ? candid_some(value.phoneNumber) : candid_none(),
        telegramId: value.telegramId ? candid_some(value.telegramId) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: Variant_sms_web_push_email_inApp;
    editBy: Principal;
    notificationType: Variant_news_risk_signal_priceTarget;
    user: Principal;
    isActive: boolean;
    frequency: Variant_monthly_immediate_daily_weekly;
}): {
    method: {
        sms: null;
    } | {
        web: null;
    } | {
        push: null;
    } | {
        email: null;
    } | {
        inApp: null;
    };
    editBy: Principal;
    notificationType: {
        news: null;
    } | {
        risk: null;
    } | {
        signal: null;
    } | {
        priceTarget: null;
    };
    user: Principal;
    isActive: boolean;
    frequency: {
        monthly: null;
    } | {
        immediate: null;
    } | {
        daily: null;
    } | {
        weekly: null;
    };
} {
    return {
        method: to_candid_variant_n51(_uploadFile, _downloadFile, value.method),
        editBy: value.editBy,
        notificationType: to_candid_variant_n52(_uploadFile, _downloadFile, value.notificationType),
        user: value.user,
        isActive: value.isActive,
        frequency: to_candid_variant_n53(_uploadFile, _downloadFile, value.frequency)
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leverage: bigint;
    tradeType: TradeType;
    riskPerTrade: bigint;
    reasoningBreakdown: string;
    noTradeReason?: string;
    createdBy: Principal;
    contractType: Variant_futures_stock_options;
    strategiesConfirmed: Array<StrategyName>;
    positionBias: PositionBias;
    positionSize: bigint;
    confidenceScore: bigint;
    target1: string;
    target2?: string;
    target3?: string;
    rewardPotential: string;
    stopLoss: string;
    timestamp: bigint;
    entryPrice: string;
    signalStatus: SignalStatus;
    riskRewardRatio: string;
    symbol: string;
    signalType: SignalType;
}): {
    leverage: bigint;
    tradeType: _TradeType;
    riskPerTrade: bigint;
    reasoningBreakdown: string;
    noTradeReason: [] | [string];
    createdBy: Principal;
    contractType: {
        futures: null;
    } | {
        stock: null;
    } | {
        options: null;
    };
    strategiesConfirmed: Array<_StrategyName>;
    positionBias: _PositionBias;
    positionSize: bigint;
    confidenceScore: bigint;
    target1: string;
    target2: [] | [string];
    target3: [] | [string];
    rewardPotential: string;
    stopLoss: string;
    timestamp: bigint;
    entryPrice: string;
    signalStatus: _SignalStatus;
    riskRewardRatio: string;
    symbol: string;
    signalType: _SignalType;
} {
    return {
        leverage: value.leverage,
        tradeType: to_candid_TradeType_n10(_uploadFile, _downloadFile, value.tradeType),
        riskPerTrade: value.riskPerTrade,
        reasoningBreakdown: value.reasoningBreakdown,
        noTradeReason: value.noTradeReason ? candid_some(value.noTradeReason) : candid_none(),
        createdBy: value.createdBy,
        contractType: to_candid_variant_n12(_uploadFile, _downloadFile, value.contractType),
        strategiesConfirmed: value.strategiesConfirmed,
        positionBias: to_candid_PositionBias_n3(_uploadFile, _downloadFile, value.positionBias),
        positionSize: value.positionSize,
        confidenceScore: value.confidenceScore,
        target1: value.target1,
        target2: value.target2 ? candid_some(value.target2) : candid_none(),
        target3: value.target3 ? candid_some(value.target3) : candid_none(),
        rewardPotential: value.rewardPotential,
        stopLoss: value.stopLoss,
        timestamp: value.timestamp,
        entryPrice: value.entryPrice,
        signalStatus: to_candid_SignalStatus_n13(_uploadFile, _downloadFile, value.signalStatus),
        riskRewardRatio: value.riskRewardRatio,
        symbol: value.symbol,
        signalType: to_candid_SignalType_n15(_uploadFile, _downloadFile, value.signalType)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeType): {
    scalping: null;
} | {
    swing: null;
} | {
    intraday: null;
} {
    return value == TradeType.scalping ? {
        scalping: null
    } : value == TradeType.swing ? {
        swing: null
    } : value == TradeType.intraday ? {
        intraday: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_futures_stock_options): {
    futures: null;
} | {
    stock: null;
} | {
    options: null;
} {
    return value == Variant_futures_stock_options.futures ? {
        futures: null
    } : value == Variant_futures_stock_options.stock ? {
        stock: null
    } : value == Variant_futures_stock_options.options ? {
        options: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalStatus): {
    active: null;
} | {
    cancelled: null;
} | {
    expired: null;
} | {
    triggered: null;
} {
    return value == SignalStatus.active ? {
        active: null
    } : value == SignalStatus.cancelled ? {
        cancelled: null
    } : value == SignalStatus.expired ? {
        expired: null
    } : value == SignalStatus.triggered ? {
        triggered: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalType): {
    buy: null;
} | {
    sell: null;
} | {
    noTrade: null;
} {
    return value == SignalType.buy ? {
        buy: null
    } : value == SignalType.sell ? {
        sell: null
    } : value == SignalType.noTrade ? {
        noTrade: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PositionBias): {
    bullish: null;
} | {
    bearish: null;
} | {
    neutral: null;
} {
    return value == PositionBias.bullish ? {
        bullish: null
    } : value == PositionBias.bearish ? {
        bearish: null
    } : value == PositionBias.neutral ? {
        neutral: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeOutcome): {
    win: null;
} | {
    loss: null;
} | {
    breakeven: null;
} | {
    noTrade: null;
} {
    return value == TradeOutcome.win ? {
        win: null
    } : value == TradeOutcome.loss ? {
        loss: null
    } : value == TradeOutcome.breakeven ? {
        breakeven: null
    } : value == TradeOutcome.noTrade ? {
        noTrade: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_sms_web_push_email_inApp): {
    sms: null;
} | {
    web: null;
} | {
    push: null;
} | {
    email: null;
} | {
    inApp: null;
} {
    return value == Variant_sms_web_push_email_inApp.sms ? {
        sms: null
    } : value == Variant_sms_web_push_email_inApp.web ? {
        web: null
    } : value == Variant_sms_web_push_email_inApp.push ? {
        push: null
    } : value == Variant_sms_web_push_email_inApp.email ? {
        email: null
    } : value == Variant_sms_web_push_email_inApp.inApp ? {
        inApp: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_news_risk_signal_priceTarget): {
    news: null;
} | {
    risk: null;
} | {
    signal: null;
} | {
    priceTarget: null;
} {
    return value == Variant_news_risk_signal_priceTarget.news ? {
        news: null
    } : value == Variant_news_risk_signal_priceTarget.risk ? {
        risk: null
    } : value == Variant_news_risk_signal_priceTarget.signal ? {
        signal: null
    } : value == Variant_news_risk_signal_priceTarget.priceTarget ? {
        priceTarget: null
    } : value;
}
function to_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_monthly_immediate_daily_weekly): {
    monthly: null;
} | {
    immediate: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == Variant_monthly_immediate_daily_weekly.monthly ? {
        monthly: null
    } : value == Variant_monthly_immediate_daily_weekly.immediate ? {
        immediate: null
    } : value == Variant_monthly_immediate_daily_weekly.daily ? {
        daily: null
    } : value == Variant_monthly_immediate_daily_weekly.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<StrategyAnalysis>): Array<_StrategyAnalysis> {
    return value.map((x)=>to_candid_StrategyAnalysis_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
